services:
  brave:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REPOSITORY:-brave/cookiemonster}:latest
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "3000:3000"
