name: Build and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  push:
    branches:
      - main

concurrency:
  group: build-deploy
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Git clone the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
        with:
          install: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.COOKIEMONSTER_AWS_ROLE_ARN }}
          role-session-name: github-actions-ecr
          aws-region: us-west-2

      - name: Login to public Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/bake-action@7a5dfed3550ca014665af2a27af8fc9d7284b9b3 # v4.5.0
        with:
          push: true
          targets: brave #,chromium
          provenance: false # https://github.com/docker/buildx/issues/1509
          sbom: false
        env:
          DOCKER_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ vars.COOKIEMONSTER_ECR_REPOSITORY }}
      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ vars.COOKIEMONSTER_LAMBDA_NAME_BRAVE }} --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ vars.COOKIEMONSTER_ECR_REPOSITORY }}:brave
