# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run lint and npm audit.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
      run: npm audit
    - run: npm run lint

    - name: Setup Environment
      run: |
        sudo apt install curl

        # Initiate model pull early to run in background
        echo "Initiating Ollama model pull..."
        curl -s -f -L http://localhost:11434/api/pull -H "Content-Type: application/json" \
          -d '{"name": "llama3", "stream": false}' &

        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
        sudo apt update
        sudo apt install brave-browser patch
        npm run rebrowser-patches

    - name: Wait for Ollama model pull
      run: |
        # Stream pull progress
        echo "Displaying Ollama model pull progress..."
        curl -s -f -L http://localhost:11434/api/pull -H "Content-Type: application/json" \
          -d '{"name": "llama3"}'

        # Wait for Ollama to be ready
        echo "Waiting for Ollama service..."
        for i in {1..5}; do
          if curl -s -f http://localhost:11434 >/dev/null 2>&1; then
            echo "Ollama is running"
            break
          fi
          echo "Attempt $i failed. Waiting before next attempt..."
          sleep 5
        done

    - name: Run Tests
      run: npm run test -- /usr/bin/brave-browser
